### ISSUE TITLE
Create Website for Shadebot

### ISSUE THREAD

**Issue by Alipoodle** [ShadeBot/ShadeBot-Discord-Bot#2]
Create site 🤷‍♂️

**Comment by PREMPRAKASHSINGH** [comment]
I can work on this one.
You are using jekyll right?
What sections should be in page like nav, footer etc?

**Comment by Alipoodle** [comment]
@PREMPRAKASHSINGH I'm sorry but one of my IRL friends is working on it using Bootstrap. 
And this issue should be moved over to the shadebot.github.io Repo due to this coming up as shadebot.github.io/Shadebot-Discord-Bot/!

**Comment by PREMPRAKASHSINGH** [comment]
Cool np :)
